Screen:

    

    MDLabel:
        text: "DreamVision"
        font_size: 64
        halign: "center"
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        
        
    MDLabel: 
        id: random_label
        text: "-"
        font_size: 64
        halign: "center"

    MDRaisedButton: 
        text: "Generate a dream"
        font_size: 32
        size: 100, 50
        halign: "center"
        on_press: app.generate_number()
