name: Perform unit tests and android build
on: [push]

jobs:
  # Build job. Builds app for Android with Buildozer
  test_project:
    name: unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9 
      - name: Install dependencies 
        run: |
          make install
      - name: Perform unit tests 
        run: |
          make test
  
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          make install
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        if: github.ref == 'refs/heads/main'
        id: buildozer
        with:
          command: buildozer -v android debug
          repository_root: .
          #workdir contains the buildozer.spec 
          workdir: 'src/dreamvision'
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: github.ref == ['refs/heads/main', 'refs/heads/fix_android_crash']
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
